version: '2'

services:

  httpd:
    image: httpd:alpine
    environment:
      VIRTUAL_HOST: your.domain.com
      LETSENCRYPT_HOST: your.domain.com
      LETSENCRYPT_EMAIL: your.email@your.domain.com
